//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class enroll
    {
        public enroll()
        {
            this.es_terceros = new HashSet<es_terceros>();
        }
    
        public byte[] template { get; set; }
        public Nullable<int> quality { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<es_terceros> es_terceros { get; set; }
    }
}
