//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class es_terceros
    {
        public string terceroid { get; set; }
        public string nombre { get; set; }
        public string tipodoc { get; set; }
        public string tipoper { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public Nullable<int> indice_id { get; set; }
    
        public virtual enroll enroll { get; set; }
    }
}
